trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

variables:
  - group: Mobile-Apps

jobs:
- job: Build
  displayName: 'Build'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'build'
      publishJUnitResults: false

- job: TagAndPublish
  displayName: 'Tag and Publish'
  dependsOn: Build
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    clean: true

  - script: |
      tag=$(git describe --tags $(git rev-list --tags --max-count=1))
      tag=${tag:-v1.0.0}
      tag=${tag//[^0-9.]/}
      newTag=$(echo $tag | awk -F. -v OFS=. '{$NF=$NF+1;} 1')
      echo "##vso[task.setvariable variable=NEW_TAG]$newTag"
      echo "##vso[task.setvariable variable=TAG]$tag"
    displayName: 'Calculate new tag'

  - script: |
      git config --global user.email "cchiriac518@gmail.com"
      git config --global user.name "cchiriac518"
      git tag v$(echo $(git tag -l "v*.*.*" | awk -F. -v OFS=. '{$(NF)=$NF+1;} 1') | awk -F. -v OFS=. '{$NF=$NF+1;} 1')
      git remote set-url origin https://cchiriac518:$(GITHUB_TOKEN)@github.com/cchiriac518/android-test.git
       git push origin HEAD:main
    displayName: 'Create and push new tag'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'publishToMavenLocal'
      publishJUnitResults: false
    displayName: 'Publish to Maven local repository'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'publish -Pversion=$(TAG)'
      publishJUnitResults: false
    displayName: 'Publish to Jitpack'