trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

variables:
  - group: Mobile-Apps

jobs:
- job: Build
  displayName: 'Build'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'build'
      publishJUnitResults: false

- job: PublishToMavenLocal
  displayName: 'Publish to Maven Local Repository'
  dependsOn: Build
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    clean: true

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'publishToMavenLocal'
      publishJUnitResults: false

- job: PublishToJitpack
  displayName: 'Publish to Jitpack'
  dependsOn: PublishToMavenLocal
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    clean: true

  - script: |
      echo "org.gradle.publish.url=https://jitpack.io" >> gradle.properties
    displayName: 'Configure Jitpack URL'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      tasks: 'publish'
      publishJUnitResults: false
