trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkPath: '/usr/lib/jvm/java-11-openjdk-amd64'
    cleanDestinationDirectory: true

- script: ./gradlew build
  displayName: 'Build'

- script: ./gradlew publish
  displayName: 'Publish'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'my-app'
