trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    curl -s "https://get.sdkman.io" | bash
    source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk install gradle
    gradle wrapper
  displayName: 'Install Gradle and Generate Wrapper'

- script: |
    ./gradlew build
  displayName: 'Build'

- script: |
    ./gradlew publish
  displayName: 'Publish'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'my-app'
