trigger:
  branches:
    exclude:
      - '*'

  paths:
    exclude:
      - version.txt

jobs:
- job: IncrementVersion
  displayName: 'Increment Version'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    persistCredentials: true

  # - script: |
  #     curl -s "https://get.sdkman.io" | bash
  #     source "$HOME/.sdkman/bin/sdkman-init.sh"
  #     sdk install gradle 8.1
  #     gradle_path=$(which gradle)
  #     $gradle_path wrapper --gradle-version 8.1 --distribution-type all

  #   displayName: 'Install Gradle'

  # - task: Gradle@2
  #   inputs:
  #     workingDirectory: '$(System.DefaultWorkingDirectory)'
  #     gradleWrapperFile: 'gradlew'
  #     tasks: 'assembleDebug'
  #   displayName: 'Build'

  # - task: Gradle@2
  #   inputs:
  #     workingDirectory: '$(System.DefaultWorkingDirectory)'
  #     gradleWrapperFile: 'gradlew'
  #     tasks: 'appCenterUpload'
  #     javaHomeOption: 'JDKVersion'
  #     jdkVersionOption: '11'
  #   displayName: 'Publish to App Center'

  - script: |
      git fetch --all
      LAST_TAG=$(git tag --sort=-v:refname | head -n 1)
      IFS='.' read -ra VERSION_PARTS <<< "$LAST_TAG"
      MAJOR=${VERSION_PARTS[0]#v}
      MINOR=${VERSION_PARTS[1]}
      PATCH=${VERSION_PARTS[2]}
      BUILD=${VERSION_PARTS[3]}
  
      PATCH=$((PATCH+1))
      BUILD=$((BUILD+1))

      if [[ $PATCH -eq 99 ]]; then
        MINOR=$((MINOR+1))
        PATCH=0
      fi

      if [[ $MINOR -eq 99 ]]; then
        MAJOR=$((MAJOR+1))
        MINOR=0
      fi

      NEW_TAG="v${MAJOR}.${MINOR}.${PATCH}.${BUILD}"
      NEW_TAG="${NEW_TAG// /}"
      echo "##vso[task.setvariable variable=NEW_TAG]$NEW_TAG"
    displayName: 'Get Last Tag and Increment Minor Version'

  - script: |
      echo "Creating Git tag $NEW_TAG"
      git tag $NEW_TAG
      git push origin --tags
    displayName: 'Create Git Tag and Push'

  - script: |
      git config --global user.email "cchiriac518@gmail.com"
      git config --global user.name "cchiriac518"
      echo $NEW_TAG > version.txt
      git add version.txt
      git commit -m "Update version.txt" --quiet
      git push origin HEAD:$(Build.SourceBranch)
    displayName: 'Update Version File'

  - script: |
      echo "##vso[task.setvariable variable=APP_VERSION]$NEW_TAG"
    displayName: 'Set Pipeline Variable for Version Tracking'


# trigger:
#   branches:
#     include:
#       - main

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - script: |
#     curl -s "https://get.sdkman.io" | bash
#     source "$HOME/.sdkman/bin/sdkman-init.sh"
#     sdk install gradle
#     gradle wrapper
#   displayName: 'Install Gradle and Generate Wrapper'

# - script: |
#     ./gradlew build
#   displayName: 'Build'

# - script: |
#     ./gradlew publish
#   displayName: 'Publish'

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Build Artifacts'
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'my-app'
