trigger:
  branches:
    exclude:
      - '*'

  paths:
    exclude:
      - version.txt

jobs:
- job: IncrementVersion
  displayName: 'Increment Version'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - script: |
      LAST_TAG=$(git describe --abbrev=0 --tags)
      VERSION_PARTS=(${LAST_TAG//./ })
      MAJOR=${VERSION_PARTS[0]}
      MINOR=${VERSION_PARTS[1]}
      PATCH=${VERSION_PARTS[2]}
      MINOR=$((MINOR+1))
      NEW_TAG="$MAJOR.$MINOR.$PATCH"
      echo "##vso[task.setvariable variable=NEW_TAG]$NEW_TAG"
    displayName: 'Get Last Tag and Increment Minor Version'

  - script: |
      echo "Creating Git tag $NEW_TAG"
      git tag $NEW_TAG
      git push origin $NEW_TAG
    displayName: 'Create Git Tag and Push'

  - script: |
      echo $NEW_TAG > version.txt
      git add version.txt
      git commit -m "Update version.txt" --quiet
      git push origin HEAD
    displayName: 'Update Version File'

  - script: |
      echo "##vso[task.setvariable variable=APP_VERSION]$NEW_TAG"
    displayName: 'Set Pipeline Variable for Version Tracking'

# trigger:
#   branches:
#     include:
#       - main

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - script: |
#     curl -s "https://get.sdkman.io" | bash
#     source "$HOME/.sdkman/bin/sdkman-init.sh"
#     sdk install gradle
#     gradle wrapper
#   displayName: 'Install Gradle and Generate Wrapper'

# - script: |
#     ./gradlew build
#   displayName: 'Build'

# - script: |
#     ./gradlew publish
#   displayName: 'Publish'

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Build Artifacts'
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'my-app'
